### ISSUE TITLE
nodejs在kubernetes中的时区设置

### ISSUE THREAD

**Issue by wangsijie** [wangsijie/blog#23]
---
title: nodejs在kubernetes中的时区设置
date: 2019-09-16 16:03:33
categories: code
tags:
  - nodejs
  - kubernetes
url: nodejs-timezone
---

kubernetes的pod中默认的时区是0时区，如果要修改时区，一般是通过mount的方式，将`/etc/localtime`映射为`/usr/share/zoneinfo/Asia/Shanghai`。

但是这种方式下，系统时区是改了，比如在bash中输出date已经是正确的，但是NodeJS应用中可能依然是0时区。这时候需要再加一个环境变量TZ即可。

```yaml
containers:
  - env:
    - name: TZ
      value: Asia/Shanghai
```
