### ISSUE TITLE
jupyterhub设置cors允许跨域

### ISSUE THREAD

**Issue by wangsijie** [wangsijie/blog#24]
---
title: jupyterhub设置cors允许跨域
date: 2019-09-29 13:40:54
categories: code
tags:
  - jupyter
  - kubernetes
url: jupyter-cors
---

使用jupyterhub作为后端kernal的时候，前端需要通过ws连接到jupyter notebook（由jupyter hub产生）。这时候在默认情况下会产生跨域的情况，需要进行一些配置。

首先是配置文件，即`jupyterhub_config.py`，一般juyputerhub的各项配置均在这个文件。 在任意位置添加以下代码

```python
origin = '*'
c.JupyterHub.tornado_settings = {
    'headers': {
        'Access-Control-Allow-Origin': origin,
    },
}
c.Spawner.args = ['--NotebookApp.allow_origin={0}'.format(origin)]
```

其中origin更改为自己的域名，注意不要保留*，否则允许所有网站的cors将会有被别人偷偷调用的风险，不仅不安全，还可能成为别人的打工仔。

另外，如果是在kubernetes中通过ingress搭建的jupyterhub，还需要一个额外的配置，

```yaml
kind: Ingress
metadata:
  annotations:
    ...
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
```
