### ISSUE TITLE
GitHub Actions 执行自定义SSH命令

### ISSUE THREAD

**Issue by wangsijie** [wangsijie/blog#26]
---
title: GitHub Actions 执行自定义SSH命令
date: 2019-10-18 09:23:19
categories: code
tags:
  - github
url: github-actions-ssh
---

观察发现Actions的机器，连接国内服务器比CircleCI的网络要更稳定，更适合做部署在国内的流水线。

总共分两步，第一步是用rsa密钥实现自动登陆远程ssh服务器，第二步才是执行命令。

## 1. 配置rsa密钥自动登陆

首先是生成ssh使用的对称rsa密钥，并把公钥保存在远程服务器的`authorized_keys`文件中，这里就不详细描述了。其中，私钥需要进入Github对应的Repo，点击Settings，Secrets，新增一个名为`SSH_PRIVATE_KEY`的键用来保存rsa私钥。

然后引入别人做好的actions脚本`webfactory/ssh-agent@v0.1.1`，读取私钥。

还有一步是配置`known-hosts`，否则会出现一个是否yes的提示卡住。记得替换下面的域名为自己的

```
- uses: webfactory/ssh-agent@v0.1.1
  with:
    ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
- name: Setup knownhosts
  run: ssh-keyscan sijie.wang >> ~/.ssh/known_hosts
```

## 2. 登陆并执行命令

引号内的内容替换为自己的命令

```
- name: Run SSH Command
  run: ssh root@sijie.wang "echo 'Hello Github Actions' > actions.log"
```
