### ISSUE TITLE
微信小程序清空按钮Button样式

### ISSUE THREAD

**Issue by wangsijie** [wangsijie/blog#28]
---
title: 微信小程序清空按钮Button样式
date: 2019-11-03 12:00:48
categories: code
tags:
  - javascript
  - 小程序
url: miniProgramButtonBorder
---

小程序中一些功能必须要用自带的button组件才能完成，比如获取授权、分享等，已经不支持用js触发了。清空button样式除了设置本身的css外，还应注意设置after，以下设置可以几乎清空一个button的样式：

```css
button {
    margin: 0;
    padding: 0;
    border: 0;
    background-color: #fff;
    color: #000;
}
button::after {
    border: 0;
}
```
