### ISSUE TITLE
kubernetes设置Pod时区

### ISSUE THREAD

**Issue by wangsijie** [wangsijie/blog#41]
---
title: kubernetes设置Pod时区
date: 2020-02-06 14:58:57
categories: code
tags:
  - kubernetes
  - docker
url: kubernetes-timezone
---

Kubernetes创建的Pod时区默认是0时区（阿里云为例），需要手动设置为北京时间，有不少文章介绍是通过挂载volume到`/etc/localtime`实现，例如：

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: timezonetest
spec:
  containers:
  - name: timezonetest
    image: busybox
    args:
    - sleep
    - "1000000"
    volumeMounts:
    - name: tz-shanghai
      mountPath: /etc/localtime
  volumes:
    - name: tz-shanghai
      hostPath:
        path: /usr/share/zoneinfo/Asia/Shanghai
```

很遗憾，这种方法会直接启动失败(仅测试1.14及以后的版本)。其实可以直接通过设置环境变量TZ实现：

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: timezonetest
spec:
  containers:
  - name: timezonetest
    image: busybox
    args:
    - sleep
    - "1000000"
    env:
    - name: TZ
      value: Asia/Shanghai
```
