### ISSUE TITLE
通过sleep命令使docker容器保持运行状态

### ISSUE THREAD

**Issue by wangsijie** [wangsijie/blog#58]
---
title: 通过sleep命令使docker容器保持运行状态
date: 2020-06-03 20:37:05
categories: code
tags:
  - docker
  - kubernetes
url: docker-sleep
---

检查docker内部的文件，一个很简单的方法就是exec进去。但默认情况下，容器在运行命令执行完毕后，就会退出。因此需要给一个永不结束的命令。

```Dockerfile
CMD sleep infinity
```

或者在Kubernetes中：

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: [ "sleep" ]
    args: [ "infinity" ]
```

参考：[https://stackoverflow.com/questions/31870222/how-can-i-keep-a-container-running-on-kubernetes](https://stackoverflow.com/questions/31870222/how-can-i-keep-a-container-running-on-kubernetes)
